functionsDirectory = "C:\\Users\\mbak\\Desktop\\BSapp\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "C:\\Users\\mbak\\Desktop\\BSapp\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npx expo export --platform web"
functions = "C:\\Users\\mbak\\Desktop\\BSapp\\netlify\\functions"

[build.environment]
NODE_VERSION = "18"
EXPO_PUBLIC_SUPABASE_URL = "https://ocdcvjpmgwsymuhtnhqc.supabase.co"
EXPO_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jZGN2anBtZ3dzeW11aHRuaHFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxMzE1NTUsImV4cCI6MjA4NTcwNzU1NX0.xOFkDQNlVEzaF9I7JSZRvBRhmLFa407VY8jPSjCHwno"
EXPO_PUBLIC_SITE_URL = "https://bsapp-management.netlify.app"

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]