/**
 * Wspolne style dla tasks/[id].tsx i jego sub-komponentow.
 * Wydzielone z tasks/[id].tsx (Faza 2 step 1).
 */
import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#f8fafc" },
  centerContainer: { flex: 1, justifyContent: "center", alignItems: "center" },
  header: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", paddingHorizontal: 16, paddingVertical: 12, backgroundColor: "#ffffff", borderBottomWidth: 1, borderBottomColor: "#e2e8f0" },
  backButton: { padding: 4 },
  headerTitle: { flex: 1, fontSize: 18, fontWeight: "600", color: "#1e293b", marginLeft: 12 },
  headerActions: { flexDirection: "row", gap: 8 },
  iconButton: { padding: 4 },
  content: { flex: 1 },
  card: { backgroundColor: "#ffffff", marginHorizontal: 16, marginTop: 16, borderRadius: 12, padding: 16, borderWidth: 1, borderColor: "#e2e8f0" },
  taskHeader: { marginBottom: 16 },
  taskTitle: { fontSize: 22, fontWeight: "700", color: "#1e293b", marginBottom: 12 },
  badges: { flexDirection: "row", gap: 8 },
  priorityBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  priorityText: { fontSize: 13, fontWeight: "600" },
  statusBadge: { paddingHorizontal: 12, paddingVertical: 6, borderRadius: 12 },
  statusText: { fontSize: 13, fontWeight: "600" },
  quickActions: { marginBottom: 16, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  quickActionsLabel: { fontSize: 13, color: "#64748b", marginBottom: 8 },
  statusButtons: { flexDirection: "row", gap: 8 },
  statusButton: { flexDirection: "row", alignItems: "center", paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, gap: 6 },
  statusButtonText: { fontSize: 13, fontWeight: "600" },
  section: { marginBottom: 16 },
  sectionTitle: { fontSize: 16, fontWeight: "600", color: "#1e293b", marginBottom: 8 },
  description: { fontSize: 14, color: "#64748b", lineHeight: 20 },
  infoGrid: { gap: 16 },
  infoItem: { gap: 6 },
  infoLabel: { flexDirection: "row", alignItems: "center", gap: 6 },
  infoLabelText: { fontSize: 13, color: "#64748b", fontWeight: "500" },
  infoValue: { fontSize: 15, color: "#1e293b", fontWeight: "600" },
  emptyText: { fontSize: 14, color: "#94a3b8", textAlign: "center", paddingVertical: 16 },
  comment: { paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: "#f1f5f9" },
  commentHeader: { flexDirection: "row", justifyContent: "space-between", marginBottom: 6 },
  commentAuthor: { fontSize: 14, fontWeight: "600", color: "#1e293b" },
  commentDate: { fontSize: 12, color: "#94a3b8" },
  commentText: { fontSize: 14, color: "#64748b", lineHeight: 20 },
  addComment: { flexDirection: "row", gap: 8, marginTop: 16 },
  commentInput: { flex: 1, backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: "#1e293b", minHeight: 44 },
  commentButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: "#2563eb", justifyContent: "center", alignItems: "center" },
  commentButtonDisabled: { opacity: 0.4 },
  errorText: { fontSize: 16, color: "#64748b" },
  modalOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "center", padding: 20 },
  modalContent: { backgroundColor: "#ffffff", borderRadius: 16, padding: 20, maxHeight: "85%" },
  modalHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 16 },
  modalTitle: { fontSize: 18, fontWeight: "700", color: "#1e293b" },
  editField: { marginBottom: 16 },
  editLabel: { fontSize: 14, fontWeight: "600", color: "#334155", marginBottom: 8 },
  editInput: { backgroundColor: "#f8fafc", borderWidth: 1, borderColor: "#e2e8f0", borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 15, color: "#1e293b" },
  editChips: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  editChip: { paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8, borderWidth: 1, borderColor: "#e2e8f0", backgroundColor: "#ffffff" },
  editChipActive: { backgroundColor: "#2563eb", borderColor: "#2563eb" },
  editChipText: { fontSize: 13, fontWeight: "600", color: "#64748b" },
  editChipTextActive: { color: "#ffffff" },
  editSaveBtn: { backgroundColor: "#2563eb", borderRadius: 8, paddingVertical: 14, alignItems: "center", marginTop: 12 },
  editSaveBtnText: { fontSize: 16, fontWeight: "600", color: "#ffffff" },
});
